elastic-host: localhost
elastic-port: 9200
training-sets:
  - uuid: acde6660-bbe6-4b4c-a8d8-327543130073
    category: "passing"
    set: "perf-ci"
validation-sets:
  - uuid: 5f93e46d-f25f-4057-8ee3-c7762005da93
    category: "failing"
    set: "perf-ci"
tests:
  - workload: "rally"
    test: "authentic-keystone"
  - workload: "rally"
    test: "create-and-list-tenants"
  - workload: "rally"
    test: "create-list-router"
  - workload: "rally"
    test: "create-list-network"
  - workload: "rally"
    test: "create-list-subnet"
  - workload: "rally"
    test: "create-list-port"
  - workload: "rally"
    test: "create-list-security-group"
  - workload: "rally"
    test: "boot-snapshot-delete"
  - workload: "rally"
    test: "boot-list"
  - workload: "rally"
    test: "create-and-delete-image"
  - workload: "rally"
    test: "netcreate-5-boot"
  - workload: "rally"
    test: "netcreate-10-boot"

metadata:
  - osp-version
# list of cloud names to grab uuid's for
clouds:
  - "microbrow-ha-2-compute-2"
  - "microbrow-ha-2-compute-1"
  - "microbrow-ha-2-compute-0"
